name: Selenide Tests with Allure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up JDK
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21

      # Step 3: Build Docker image
      - name: Build Docker image
        run: docker build -t selenide-tests .

      # Step 4: Run Selenide tests inside Docker
      - name: Run Selenide tests
        run: docker run --rm -v ${{ github.workspace }}/target:/app/target selenide-tests

      # Step 5: Install Allure CLI
      - name: Install Allure CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          wget https://github.com/allure-framework/allure2/releases/download/2.29.0/allure-2.29.0.zip
          unzip allure-2.29.0.zip -d /opt/
          sudo ln -s /opt/allure-2.29.0/bin/allure /usr/bin/allure
          allure --version

      # Step 6: Generate Allure report
      - name: Generate Allure Report
        run: allure generate ./target/allure-results --clean -o target/allure-report

      # Step 7: Deploy Allure report to GitHub Pages
      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: target/allure-report
          publish_branch: gh-pages
